- name: Install yum-utils
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Install required system packages
  ansible.builtin.yum:
    name:
      - git
      - wget
      - curl
    state: present