- name: Add HashiCorp repository
  ansible.builtin.command: yum-config-manager --add-repo {{ vault_repo_url }}
  args:
    creates: /etc/yum.repos.d/hashicorp.repo

- name: Import HashiCorp GPG key
  ansible.builtin.rpm_key:
    key: "{{ vault_gpg_key }}"
    state: present

- name: Install HashiCorp packages
  ansible.builtin.yum:
    name: "{{ hashicorp_packages }}"
    state: present