- name: Ensure Ansible configuration directory exists
  ansible.builtin.file:
    path: /etc/ansible
    state: directory
    mode: '0755'

- name: Deploy Ansible configuration file
  ansible.builtin.template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
    mode: '0644'