- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required system packages
  ansible.builtin.apt:
    name: "{{ required_packages }}"
    state: present