python_version: "3.11"
vault_repo_url: "https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
vault_gpg_key: "https://rpm.releases.hashicorp.com/gpg"

ansible_version: ">=8.0.0,<9.0.0"
hashicorp_vault_version: "1.15.0"

# Users to create (referenced in users.yml)
create_users:
  - eric
  - ansible

# SSH allowed IPs for iptables (add your actual IPs)
ssh_allowed_ips:
  - "YOUR_IP_ADDRESS"  # Replace with your actual IP

required_packages:
  - yum-utils
  - git
  - wget
  - curl

python_packages:
  - python3.11

pip_packages:
  - "hvac>=1.2.0,<2.0.0"
  - "PyMySQL>=1.0.0"
  - "jmespath>=1.0.0"
  - "passlib[bcrypt]>=1.7.0"
  - "pywinrm>=0.4.0"
  - "requests>=2.28.0"
  - "cryptography>=3.4.0"

hashicorp_packages:
  - vault