---
- name: Setup Ansible server (RHEL/CentOS)
  hosts: ansible_rhel

  pre_tasks:
    - name: Check if essential variables are defined
      assert:
        that:
          - hostname is defined
        fail_msg: "Essential variables are not defined."
      tags: always

  roles:
    - name: ansible-setup-rhel
      tags: ansible-setup-rhel

    - name: ssh-public-keys
      tags: ssh-public-keys