---
- name: Setup Ansible server (Ubuntu/Debian)
  hosts: ansible_ubuntu

  pre_tasks:
    - name: Check if essential variables are defined
      assert:
        that:
          - hostname is defined
        fail_msg: "Essential variables are not defined."
      tags: always

  roles:
    - name: ansible-setup-ubuntu
      tags: ansible-setup-ubuntu

    - name: ssh-public-keys
      tags: ssh-public-keys