---
- name: Setup Ansible server
  hosts: ansible

  pre_tasks:
    - name: Check if essential variables are defined
      assert:
        that:
          - server_id is defined
          - hostname is defined
        fail_msg: "Essential variables are not defined."
      tags: always

  roles:
  - name: ansible-setup
    tags: ansible-setup

  - name: ssh-public-keys
    tags: ssh-public-keys